source("scripts/build-config.R")
source("scripts/export-helpers.R")
.libPaths(build_library, include.site = FALSE)
options(repos = build_repositories, timeout = 600)

if (!requireNamespace("shinylive", quietly = TRUE) ||
  as.character(packageVersion("shinylive")) != shinylive_version) {
  stop("Run Rscript scripts/setup-build.R before exporting.", call. = FALSE)
}
description <- packageDescription("enrollcast")
if (!identical(description$Repository, unname(build_repositories["localopen"]))) {
  stop("Build enrollcast must be installed from localopen.r-universe.dev.",
    call. = FALSE)
}

local({
  stage <- tempfile("enrollment-app-")
  output <- tempfile("enrollment-site-")
  on.exit(unlink(c(stage, output), recursive = TRUE))
  stage_app(".", stage)
  shinylive::export(stage, output,
    wasm_packages = TRUE, package_cache = FALSE, max_filesize = "100M",
    assets_version = shinylive_assets,
    template_params = list(title = "Enrollment Projections Calculator"),
    quiet = FALSE)

  wasm_root <- file.path(output, "shinylive", "webr")
  metadata <- readRDS(file.path(wasm_root, "packages", "metadata.rds"))
  validate_wasm(metadata, wasm_root)
  if (!startsWith(metadata$enrollcast$assets[[1]]$url,
    paste0(build_repositories["localopen"], "/"))) {
    stop("Wasm enrollcast did not resolve from the canonical repository.")
  }
  packages <- lapply(metadata[sort(names(metadata), method = "radix")], function(package) {
    path <- file.path(wasm_root, package$path)
    list(version = package$assets[[1]]$version,
      url = as.character(package$assets[[1]]$url),
      sha256 = sha256_file(path))
  })
  manifest <- list(shinylive = shinylive_version, assets = shinylive_assets,
    webr_r = webr_r_version, runtime = runtime_hashes(output), packages = packages)
  lockfile <- "scripts/wasm-lock.json"
  if ("--update-wasm-lock" %in% commandArgs(trailingOnly = TRUE)) {
    jsonlite::write_json(manifest, lockfile, auto_unbox = TRUE, pretty = TRUE)
  } else {
    if (!file.exists(lockfile) ||
      !identical(manifest, jsonlite::read_json(lockfile))) {
      if (file.exists(lockfile)) {
        message(paste(all.equal(manifest, jsonlite::read_json(lockfile)),
          collapse = "\n"))
      }
      stop(paste(
        "Wasm artifacts differ from scripts/wasm-lock.json.",
        "Review package changes, then export with --update-wasm-lock",
        "and rerun native and browser tests before deployment."
      ), call. = FALSE)
    }
  }
  jsonlite::write_json(manifest, file.path(output, "build-info.json"),
    auto_unbox = TRUE, pretty = TRUE)
  writeLines("Generated by scripts/export-shinylive.R",
    file.path(output, ".enrollcast-export"))
  writeLines(character(), file.path(output, ".nojekyll"))
  publish_site(output)
  message("Verified static site exported to site/.")
})
